INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Bryan Ponce','2000-03-20','066710096','tbeck@msn.com');
INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Kelly Pearson','1992-02-21','06794448215','unreal@msn.com');
INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Michael Ramirez','1997-03-12','0625671228','ajohnson@comcast.net');
INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Anthony Rodriguez','1995-04-02','06787134538','kohlis@gmail.com');
INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Veronica Grimes','1992-02-05','063923419','euice@sbcglobal.net');
INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Nicholas Phillips','1990-07-06','064357680','mschilli@att.net');
INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Andrew White','1999-03-04','06767396146','noahb@gmail.com');
INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Sabrina Jackson','1996-05-06','06716158212','atmarks@mac.com');
INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Andrew Hicks','1984-02-09','0670461812','staffelb@live.com');
INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Mrs. Katrina Rogers','1987-03-10','06769560246','tjensen@msn.com');
INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Terry Wright','1977-04-12','06758118776','mrdvt@icloud.com');
INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Bryan Davis','1997-05-12','0675399613','multiplx@comcast.net');
INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Megan Williamson','1987-06-13','06776132302','ajohnson@outlook.com');
INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Kevin Mcknight','1967-02-21','0685170969','yfreund@aol.com');
INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Julie Conner','1977-02-22','066750616','corrada@yahoo.com');
INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Brian Pearson','1985-02-28','06779825207','donev@gmail.com');
INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Paul Brown','1998-05-25','0677768186','aschmitz@mac.com');
INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Brian Warren','1983-06-29','0656699031','sblack@att.net');
--INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Nicole Humphrey','1982-02-15','063539706','rfoley@mac.com');
--INSERT INTO job_candidate(name,date_of_birth,contact_number,email) VALUES ('Nathan Wilson','1983-07-19','06787991501','jlbaumga@me.com');


INSERT INTO skill(name) VALUES ('Java programming');
INSERT INTO skill(name) VALUES ('C# programming');
INSERT INTO skill(name) VALUES ('Database design');
INSERT INTO skill(name) VALUES ('QA development');
INSERT INTO skill(name) VALUES ('English language');
INSERT INTO skill(name) VALUES ('German language');
INSERT INTO skill(name) VALUES ('Russian language');

INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (1,2);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (1,4);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (2,1);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (2,4);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (4,6);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (4,7);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (4,1);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (5,6);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (5,2);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (6,1);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (6,6);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (6,3);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (7,1);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (7,2);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (8,6);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (8,4);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (8,3);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (9,4);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (9,6);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (9,3);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (10,5);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (10,7);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (10,4);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (11,2);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (11,3);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (11,1);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (12,2);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (12,7);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (12,4);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (13,1);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (13,2);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (14,6);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (14,2);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (15,7);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (16,6);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (16,5);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (16,1);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (16,2);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (18,1);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (18,2);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (18,3);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (18,6);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (18,5);
INSERT INTO job_candidate_skill(job_candidate_id,skill_id) VALUES (18,4);
